### ISSUE TITLE
🚀[Feature] Additional Secret Vault providers for secrets

### ISSUE THREAD

**Issue by Manbearpiet** [PSModule/GitHub#82]
Hey, fantastic project; it is very complete and up-to-date.

How do I use Azure KeyVault as the secret store? Is there any short guidance on how to do so?

I tried editing SecretVault.psd1 to:
```powershell
@{
    Name   = 'MyVault'                      # $script:SecretVault.Name
    Type   = 'Az.KeyVault' # $script:SecretVault.Type
    Prefix = 'GHPS_'                          # $script:SecretVault.Prefix
}
```
This gives issues with the Az.KeyVault Vault provider, because the secrets set need to adhere to:
```ps
Set-Secret: 'secretName' does not match expected pattern '^[0-9a-zA-Z-]+$'.
```

Then I tried to set the SecretVault.psd1 to:
```powershell
@{
    Name   = 'MyVault'                      # $script:SecretVault.Name
    Type   = 'Az.KeyVault' # $script:SecretVault.Type
    Prefix = 'GHPS-'                          # $script:SecretVault.Prefix
}
```
This gives a new set of problems:
```powershell
connect-gitHubAccount -AccessToken -Silent -Owner WeAreInSpark
ConvertTo-HashTable: Cannot bind argument to parameter 'InputObject' because it is null.
Join-Object: Cannot bind argument to parameter 'Overrides' because it is null.
Set-SecretInfo: Cannot add secret metadata 'GHPS-AccessToken' to vault 'MyVault: The vault does not support the Set-SecretInfo function.
ConvertTo-HashTable: Cannot bind argument to parameter 'InputObject' because it is null.
Join-Object: Cannot bind argument to parameter 'Overrides' because it is null.
Set-SecretInfo: Cannot add secret metadata 'GHPS-RefreshToken' to vault 'MyVault: The vault does not support the Set-SecretInfo function.
```
So to support Azure KeyVault some changes need to be made:
- The secret metadata needs to be optional
- The secrets need to be able to be named without underscores

If I ignore the errors on the metadata the module doesn't throws an error:

```powershell
get-githubworkflow -Owner WeAreInSpark -Repo Testrepo
Join-Object: Cannot bind argument to parameter 'Main' because it is null.
Join-Object: Cannot bind argument to parameter 'Main' because it is null.
Invoke-GitHubAPI:
Invoke-GitHubAPI: ----------------------------------
Invoke-GitHubAPI:
Invoke-GitHubAPI: Request:
Invoke-GitHubAPI:
Invoke-GitHubAPI: StatusCodeVariable      : APICallStatusCode
Invoke-GitHubAPI: Method                  : 1
Invoke-GitHubAPI: ContentType             : application/vnd.github+json; charset=utf-8
Invoke-GitHubAPI: Authentication          : Bearer
Invoke-GitHubAPI: FollowRelLink           : True
Invoke-GitHubAPI: HttpVersion             : @{Major=2; Minor=0; Build=-1; Revision=-1; MajorRevision=-1; MinorRevision=-1}
Invoke-GitHubAPI: ResponseHeadersVariable : APICallResponseHeaders
Invoke-GitHubAPI: Token                   : @{Length=0}
Invoke-GitHubAPI: Uri                     : /repos/WeAreInSpark/Testrepo/actions/workflows?per_page=30
Invoke-GitHubAPI: Headers                 : @{Accept=application/vnd.github+json; charset=utf-8}
Invoke-GitHubAPI:
Invoke-GitHubAPI:
Invoke-GitHubAPI: ----------------------------------
Invoke-GitHubAPI:
Invoke-GitHubAPI: Message:
Invoke-GitHubAPI: This operation is not supported for a relative URI.
Invoke-GitHubAPI:
Invoke-GitHubAPI: ----------------------------------
Invoke-GitHubAPI:
Invoke-GitHubAPI: Response:
Invoke-GitHubAPI:
Invoke-GitHubAPI: ----------------------------------
Invoke-GitHubAPI:
Invoke-GitHubAPI:
Exception: This operation is not supported for a relative URI.

Get-GitHubRepository -Owner WeAreInSpark -Repo Testrepo
Join-Object: Cannot bind argument to parameter 'Main' because it is null.
Join-Object: Cannot bind argument to parameter 'Main' because it is null.
Invoke-GitHubAPI:
Invoke-GitHubAPI: ----------------------------------
Invoke-GitHubAPI:
Invoke-GitHubAPI: Request:
Invoke-GitHubAPI:
Invoke-GitHubAPI: StatusCodeVariable      : APICallStatusCode
Invoke-GitHubAPI: Method                  : 1
Invoke-GitHubAPI: ContentType             : application/vnd.github+json; charset=utf-8
Invoke-GitHubAPI: Authentication          : Bearer
Invoke-GitHubAPI: FollowRelLink           : True
Invoke-GitHubAPI: HttpVersion             : @{Major=2; Minor=0; Build=-1; Revision=-1; MajorRevision=-1; MinorRevision=-1}
Invoke-GitHubAPI: ResponseHeadersVariable : APICallResponseHeaders
Invoke-GitHubAPI: Token                   : @{Length=0}
Invoke-GitHubAPI: Uri                     : /repos/WeAreInSpark/Testrepo
Invoke-GitHubAPI: Headers                 : @{Accept=application/vnd.github+json; charset=utf-8}
Invoke-GitHubAPI:
Invoke-GitHubAPI:
Invoke-GitHubAPI: ----------------------------------
Invoke-GitHubAPI:
Invoke-GitHubAPI: Message:
Invoke-GitHubAPI: This operation is not supported for a relative URI.
Invoke-GitHubAPI:
Invoke-GitHubAPI: ----------------------------------
Invoke-GitHubAPI:
Invoke-GitHubAPI: Response:
Invoke-GitHubAPI:
Invoke-GitHubAPI: ----------------------------------
Invoke-GitHubAPI:
Invoke-GitHubAPI:
Exception: This operation is not supported for a relative URI.
```

Also I'd like to use this in a script, but it tries to open a webpage at:
```powershell
            Start-Process 'https://github.com/settings/tokens'
```
This doesn't work on a Azure Function, it would be great if there was a switch param to skip this line.

**Comment by MariusStorhaug** [comment]
Hi @Manbearpiet, thank you for testing it out.

We can for sure add that, what I didn't really test all use cases for how to connect to other secret stores, but thinking this is something that should be solvable. Can see if I can do something like this in the Config commands so that you can override the default. Currently the defaults are indeed not exposed.

Also thinking of decoupling the config store from the module and use it as a separate dependent module so that this can be added to other modules I have in the works. I.e., AzureDevOps.

Apologies for being late on the ball, didn't have any notifications about new issues coming in, but thats also fixed now :)

**Comment by Manbearpiet** [comment]
> Hi @Manbearpiet, thank you for testing it out.
> 
> We can for sure add that, what I didn't really test all use cases for how to connect to other secret stores, but thinking this is something that should be solvable. Can see if I can do something like this in the Config commands so that you can override the default. Currently the defaults are indeed not exposed.
> 
> Also thinking of decoupling the config store from the module and use it as a separate dependent module so that this can be added to other modules I have in the works. I.e., AzureDevOps.
> 
> Apologies for being late on the ball, didn't have any notifications about new issues coming in, but thats also fixed now :)

We have a similar module for Azure DevOps: https://github.com/WeAreInSpark/AzureDevOpsPowerShellAPI
It uses access tokens instead of PAT's so support for users and apps (instead of 'service accounts' boo! 👻).
Don't worry about the response; the module is awesome, and it's not as if you have a paid service 😄.

**Comment by MariusStorhaug** [comment]
@Manbearpiet Sorry for taking time to get to this again. Actively looking into this now. Have mainly been working on the framework and splitting up into sizable chunks and making it faster to iterate on. 

Will be looking with fresh eyes on the function to get and set configuration, using secret vaults only and maybe less focus on metadata or change how metadata is used. Will be testing multiple vaults as I do this and will be working on a separate module to solve this. The module is currently called `Store`. Thought is to have something that can use the local `SecretStore`, `AzureKeyVault`; basically only using the spec for a vault as foundation for the function. Will see if i can stay away from the underscores as this is a specific limitation to keyvault secrets i think.

The `Start-Process 'https://github.com/settings/tokens'` should only be run if using a interactive PAT token signin approach (running `Connect-GitHubAccount` with `-AccessToken`, `-PAT` or `-Token`) and not the sPAT token approach using the default environment variables (`GH_TOKEN`, `GITHUB_TOKEN`).

Feel free to follow the progress on [Store](https://psmodule.io/Store).

**Comment by MariusStorhaug** [comment]
Hi @Manbearpiet: Could you please check out the new version and see if it suits your needs?

Try the following:

1. Add the installation token to a environment variable called 'GITHUB_TOKEN' og 'GH_TOKEN'.
2. Run the following commands:
```powershell
Import-Module GitHub
Set-GitHubConfig -SecretVaultName 'YouKeyVault' -SecretVaultType 'Az.KeyVault'
Connect-GitHubAccount
```

Awaiting your feedback to see if I can close this issue or not. :) Again, thank you for suggestions on how to make this better!

**Comment by Manbearpiet** [comment]
Ofcourse, I will check this tomorrow!

**Comment by Manbearpiet** [comment]
```powershell
Import-Module GitHub
✓ Logged in as system!

Set-GitHubConfig -SecretVaultName 'cf6795dd388a' -SecretVaultType 'Az.KeyVault'
Connect-GitHubAccount
✓ Logged in as system!

Get-GitHubOrganization
Get-SecretInfo: Vault not found in registry: cf6795dd388a

$parameters = @{
   Name = 'Azure'
   ModuleName = 'Az.KeyVault'
   VaultParameters = @{
       AZKVaultName = 'cf6795dd388a'
       SubscriptionId = (Get-AzContext).Subscription.Id
   }
   DefaultVault = $true
 }
Register-SecretVault @parameters

Set-GitHubConfig -SecretVaultName 'Azure' -SecretVaultType 'Az.KeyVault'
Connect-GitHubAccount
✓ Logged in as system!

Get-GitHubRepository -Owner WeAreInSpark | where visibility -eq private
# Returns my repo info yay
Get-GitHubWorkflow -Owner WeAreInSpark -Repo myprivaterepo
# returns my workflow info
```
It works fine! I need some time to test all my flows thoroughly, but it looks fine to me!
Thank you for your effort!
