### ISSUE TITLE
🌞 [Other]: Use GraphQL

### ISSUE THREAD

**Issue by MariusStorhaug** [PSModule/GitHub#94]
### Description

Change existing REST API calls to use GraphQL API calls.

**Comment by Manbearpiet** [comment]
Last when I checked, workflows aren't supported on the GraphQL API. 
So do mind that.

**Comment by MariusStorhaug** [comment]
Closing this for now as the need for GraphQL is on a pr use basis. I.e. As @Manbearpiet writes, I wouldnt swap workflow functions for GraphQL mutations now, but use it for stuff where it is the only thing that provides the functionality. I.e. Get-GitHubViewer => Get info about singed in user or app installation; or Get-GitHubEnterpriseOrganizations -> onyl available as a query on enterprise + organization. Also there is no support for JWT based auth, so anything that happens as an authenticated GitHub App (not installation) needs to use rest. So ye. Closing as this issue is in-actionable. :)
